### PR TITLE
Upgrade some dependencies with security vulnerabilities

### PR DESCRIPTION
**Pull request by dustinryerson**
Reduces known dependency security vulnerabilities by 73%.

Pre-upgrade Yarn audit: `Severity: 201 Low | 1100 Moderate | 6 High` **(1307 total)**

upgrade lodash@^4.17.11
Yarn audit: `Severity: 201 Low | 1099 Moderate | 6 High` **(1306 total)**

upgrade jest@^24.1.0
Yarn audit: `Severity: 145 Low | 917 Moderate | 5 High` **(1067 total)**

upgrade node-sass@^4.11.0
Yarn audit: `Severity: 145 Low | 908 Moderate | 5 High` **(1058 total)**

upgrade webpack-cli@^3.2.3
Yarn audit: `Severity: 143 Low | 508 Moderate | 5 High` **(656 total)**

upgrade webpack-dev-server@^3.2.1
Yarn audit: `Severity: 143 Low | 507 Moderate | 2 High` **(652 total)**

upgrade mithril-jest@^1.0.3
Yarn audit: `Severity: 25 Low | 331 Moderate` **(356 total)**

### CODE REVIEW

**Comment by karenetheridge** [comment]
Does buildbot/conch-ui-docker need fixing?

**Comment by dustinryerson** [comment]
I'm in the process of upgrading some other packages, which I've confirmed fixes the buildbot error.

**Comment by dustinryerson** [comment]
Latest Yarn audit: `Severity: 1 Low`

**Comment by dustinryerson** [comment]
@perigrin this is ready for review whenever you have some time.

**Pull request merged**
